//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wordlearn.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbwordnewEntities : DbContext
    {
        public dbwordnewEntities()
            : base("name=dbwordnewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblengWord> tblengWords { get; set; }
        public virtual DbSet<tblLearning> tblLearnings { get; set; }
        public virtual DbSet<tbltrWord> tbltrWords { get; set; }
    }
}
