//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wordlearn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltrWord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbltrWord()
        {
            this.tblLearnings = new HashSet<tblLearning>();
        }
    
        public int trID { get; set; }
        public string trWord { get; set; }
        public string trSentences { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLearning> tblLearnings { get; set; }
    }
}
